### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by screwfaze** [dkanada/gelli#102]
Latest release crashes when playing a song and opening any playlist. Have to clear app data to connect again.

**Comment by dkanada** [comment]
I thought this must be a universal issue but I just checked and have no such crashes. Any chance you can grab some logs or something to point me in the right direction? Maybe a server version as well to pinpoint the issue.

**Comment by dkanada** [comment]
After some more thinking, I pushed a new release with a possible fix. Let me know if the release APK is working for you now.

**Comment by poulpor** [comment]
Thank you very much for investigating, this new release is working good, no more crash when I select an album and the tracks are playing perfectly. Your app is getting better and better and is the best Jellyfin music companion.

**Comment by screwfaze** [comment]
I am afraid this is still happening started after a while using the app

**Comment by ssepi0l-pv** [comment]
Hey, sorry for necrobumping, but today after I installed the version 1.3.0 (from F-Droid), the app has been crashing multiple times when I try to hear a song, then making the app completely unusable. The only way around that, is like poulpor said: cleaning cache/data and then it's ready to go. But, I am still unable to hear music properly (because the issue persists). 

After that, I went to F-Droid to check if any other issue had been open about this problem. Here am I. Although, I did check the version 1.3.1 (release) and same thing happened. At this moment I'm installing the debug (1.3.1) version. Here's what I got:

`Gelli App crashed in com.dkanada.gramophone.service.MusicService$PlaybackHandler
Version code: 14
Version name: 1.3.1
Stack Trace: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replaceAll(java.lang.String, java.lang.String)' on a null object reference
	at com.dkanada.gramophone.util.MusicUtil.ascii(MusicUtil.java:89)
	at com.dkanada.gramophone.util.MusicUtil.getFileUri(MusicUtil.java:81)
	at com.dkanada.gramophone.service.playback.LocalPlayer.appendDataSource(LocalPlayer.java:121)
	at com.dkanada.gramophone.service.playback.LocalPlayer.queueDataSource(LocalPlayer.java:117)
	at com.dkanada.gramophone.service.MusicService.prepareNextImpl(MusicService.java:525)
	at com.dkanada.gramophone.service.MusicService.access$1300(MusicService.java:77)
	at com.dkanada.gramophone.service.MusicService$PlaybackHandler.handleMessage(MusicService.java:1158)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.os.HandlerThread.run(HandlerThread.java:67)`
	
Hope it helps you mate! I'll be expecting your response :)

**Comment by dkanada** [comment]
I saw this once or twice during development but it sounds like you're experiencing it much more frequently. I don't think this issue is related, but I'll open it again anyways and track the progress here.

**Comment by ssepi0l-pv** [comment]
Yeah... I downgraded the app, though. I'll wait for it to be patched and stuff to update again :)

**Comment by Stiralbios** [comment]
Hello, 
I use fdroid, I have the issue since the 1.3.0 before it was working flawlessly for me.
Where are the logs located ? If I can get them I would share them, maybe it could help you.

**Comment by barracuda777** [comment]
I compiled the latest source code, the random crashing issue is gone, I have tried all the songs that used to crash Gelli but now works perfectly, this Commit https://github.com/dkanada/gelli/commit/24cb549681145171b27a9cce929531db5ada4bd8 have fixed it. Thank you

**Comment by ssepi0l-pv** [comment]
In the release version 1.3.1 the app crashed for me. Well, I was looking into updating my app the the latest release (1.3.2 at this time). I did it (from version 1.2.4) and it still crashes from time to time. I will send the debug crash log when I get back home. Either way, it was working for a few hours... but then nope, didn't work anymore I downgraded to 1.2.4.

**Comment by dkanada** [comment]
Sounds like at least one of the new issues was fixed then. @Stiralbios was your crash fixed with the release yesterday?

@ssepi0l-pv once I take a look at the logs I'll try and fix your issue for the next release.

**Comment by Stiralbios** [comment]
I downloaded the 1.3.2 version and tried to mistreat the app as much as possible. I didn't have any crash. Thank you :)

**Comment by barracuda777** [comment]
For anyone who are still having random crashes, do a re-scan and replace all metadata of your Music folder on Jellyfin, I have observed that if I moved some files around and then tried to play the file that is not there anymore the app crashes needing a reset, other than that, with a newly scanned data base, the app works flawlessly.  Thanks @dkanada for this wonderful app.
