### ISSUE TITLE
Images break when Connected directly via IPv6

### ISSUE THREAD

**Issue by pstn** [dkanada/gelli#57]
For testing purposes I connected to my jellyfin instance directly via an IPv6 Address (Server: `http://[::1]` would be localhost in the pattern I used) and it worked but no images loaded. It works fine when using IPv4 or IPv6 with a DNS entry.

**Comment by ThibaultNocchi** [comment]
Maybe this could be linked to #30?

**Comment by dkanada** [comment]
Has this been resolved in the latest versions? There have been a lot of library updates that might have affected IPV6 support.

**Comment by dkanada** [comment]
@pstn pinging one more time before I close the issue for now. I haven't seen any other issues with IPV6 - maybe you're using a reverse proxy somewhere that affects the results?

**Comment by pstn** [comment]
The issue still persists. I have a proxy that serves the jellyfin on both IPv6 and IPv4. If I connect via a domain name, IPv6 is used and gelli works fine, same as when I input the raw IPv4 of the proxy. Only when I use the raw IPv6 of that same proxy, no pictures are loaded. The rest of the site works fine.

**Comment by dkanada** [comment]
Searched around for a bit and it seems that this is a library issue. One of the reports was [closed](https://github.com/bumptech/glide/issues/2348) and another one is still [pending a response](https://github.com/bumptech/glide/issues/4369) from the developers. I also found what seems to be the [root cause](https://programmersought.com/article/59101040107) and will report it upstream to see what happens.

**Comment by pstn** [comment]
Thanks! Good luck with the report.

**Comment by dkanada** [comment]
As a quick test, can you try the same address but without any square brackets? I think this will only work if you're not using a port but those seem to be causing the issue.

**Comment by pstn** [comment]
I can't connect to the server at all without providing square brackets. I always get a "can't connect to server" error message even when serving jellyfin on both `tcp/80` and `tcp/8096`.
